import fs from "node:fs";
import path from "node:path";
const root = path.resolve(decodeURIComponent(new URL("..", import.meta.url).pathname).replace(/^\/(.:)/, "$1"));
const required = ["layout/theme.liquid","templates/index.json","templates/collection.json","templates/product.json","templates/page.about.json","templates/page.preparation.json","templates/page.contact.json","templates/cart.json","sections/header.liquid","sections/footer.liquid","sections/hero-studio.liquid","sections/featured-services.liquid","sections/process.liquid","sections/main-booking-product.liquid","sections/main-collection.liquid","sections/main-rich-page.liquid","sections/main-contact.liquid","sections/main-cart.liquid","assets/studio.css","assets/studio.js","data/service-portfolio-images.json","data/shopify-services.csv","config/settings_schema.json","config/settings_data.json","locales/en.default.json","scripts/build.mjs","vercel.json"];
let errors = [];
for (const file of required) if (!fs.existsSync(path.join(root, file))) errors.push(`Missing ${file}`);
for (const dir of ["templates", "config", "locales"]) for (const file of fs.readdirSync(path.join(root, dir)).filter((name) => name.endsWith(".json"))) try { JSON.parse(fs.readFileSync(path.join(root, dir, file), "utf8")); } catch (error) { errors.push(`Invalid JSON ${dir}/${file}: ${error.message}`); }
const product = fs.readFileSync(path.join(root, "sections/main-booking-product.liquid"), "utf8");
for (const needle of ["properties[Appointment date]", "properties[Appointment time preference]", "properties[Preparation acknowledged]", "content_for 'blocks'", '"type":"@app"']) if (!product.includes(needle)) errors.push(`Booking section missing ${needle}`);
const previewFiles = fs.readdirSync(path.join(root, "preview")).filter((file) => file.endsWith(".html"));
const previewBundle = previewFiles.map((file) => fs.readFileSync(path.join(root, "preview", file), "utf8")).join("\n");
if (/https?:\/\/[^"']+\.(png|jpg|jpeg|webp)/i.test(previewBundle)) errors.push("External image URL in preview pages");
const script = fs.readFileSync(path.join(root, "assets/studio.js"), "utf8");
for (const token of ["localStorage", "bambiStudioAppointmentRequest", "data-preview-cart", "Clear request", "Edit request"]) if (!script.includes(token) && !previewBundle.includes(token)) errors.push(`Persisted request flow missing ${token}`);
const services = [["Traditional Frontal ponytail (hair included)", "R1 800,00"], ["Fluffy frontal ponytail (hair included)", "R2 800,00"], ["Clean installation + Curling", "R950,00"], ["Clean installation + Straightening", "R750,00"], ["Half up half down", "R1 150,00"], ["Bob installation 10-14 inch", "R680,00"], ["HD lace Lagos frontal ponytail (hair included)", "R3 350,00"]];
const csv = fs.readFileSync(path.join(root, "data/shopify-services.csv"), "utf8"), catalogueSource = `${previewBundle}\n${script}\n${csv}`;
for (const [title, price] of services) for (const fact of [title, price]) if (!catalogueSource.includes(fact)) errors.push(`Catalogue fact missing: ${fact}`);
const servicesPreview = fs.readFileSync(path.join(root, "preview/services.html"), "utf8"), cards = [...servicesPreview.matchAll(/<a\s+class="service-card[^"]*"[\s\S]*?<\/a>/g)];
if (cards.length !== services.length) errors.push(`Expected ${services.length} static service cards, found ${cards.length}`);
const homeCards = [...fs.readFileSync(path.join(root, "preview", "index.html"), "utf8").matchAll(/<a\s+class="service-card"[\s\S]*?<\/a>/g)];
if (homeCards.length !== services.length) errors.push(`Expected all ${services.length} services on the home page, found ${homeCards.length}`);
for (const [index, card] of cards.entries()) { if (!/<img\s+[\s\S]*?src="\.\.\/assets\/service-portfolio\/[^\"]+"[\s\S]*?>/.test(card[0])) errors.push(`Static service card ${index + 1} is missing a local portfolio image`); const alt = card[0].match(/<img\s+[\s\S]*?alt="([^"]*)"[\s\S]*?>/)?.[1]?.trim(); if (!alt || alt.length < 12) errors.push(`Static service card ${index + 1} is missing meaningful alt text`); }
const manifest = JSON.parse(fs.readFileSync(path.join(root, "data/service-portfolio-images.json"), "utf8"));
if (Object.keys(manifest.services || {}).length !== services.length) errors.push("Portfolio image manifest must map exactly seven services");
for (const [slug, service] of Object.entries(manifest.services || {})) { if (!fs.existsSync(path.join(root, "assets", service.asset))) errors.push(`Missing local service image for ${slug}`); if (!script.includes(`image: "${service.asset}"`)) errors.push(`Booking image does not match manifest for ${slug}`); for (const asset of service.supportingAssets || []) if (!fs.existsSync(path.join(root, "assets", asset))) errors.push(`Missing supporting image for ${slug}`); }
if (manifest.services?.["clean-installation-straightening"]?.asset !== "service-portfolio/clean-straightening-face-blurred.png") errors.push("Straightening service must use the privacy-edited portfolio image");
for (const fact of ["2 hours 40 minutes", "3 hours", "2 hours", "1 hour 40 minutes", "Please come with your wig lines already done.", "Hair includes a pre-bleached, pre-plucked transparent lace + 2 synthetic bundles."]) if (!catalogueSource.includes(fact)) errors.push(`Updated service fact missing: ${fact}`);
if (previewBundle.includes("<option>Moses</option>")) errors.push("Unavailable stylist Moses remains selectable");
if (fs.readdirSync(path.join(root, "assets", "service-portfolio")).filter((file) => /^image\d+\.(jpeg|png)$/i.test(file)).length !== 18) errors.push("Expected all 18 merchant-supplied portfolio images in runtime assets");
for (const source of [previewBundle, script, ...["sections/main-collection.liquid", "sections/featured-services.liquid", "sections/hero-studio.liquid", "sections/main-booking-product.liquid"].map((file) => fs.readFileSync(path.join(root, file), "utf8"))]) if (source.includes("booksy-services/")) errors.push("Inactive Booksy assets must not be used at runtime");
for (const liquidSection of ["sections/main-collection.liquid", "sections/featured-services.liquid"]) { const source = fs.readFileSync(path.join(root, liquidSection), "utf8"); for (const token of ["product.featured_image", "image_tag", "fallback_asset", "asset_url", "alt:"]) if (!source.includes(token)) errors.push(`${liquidSection} is missing image fallback support: ${token}`); }
for (const expectedAsset of Object.values(manifest.services).map((entry) => entry.asset)) if (!fs.readFileSync(path.join(root, "sections/main-collection.liquid"), "utf8").includes(expectedAsset)) errors.push(`Shopify collection fallback missing ${expectedAsset}`);
const stylesheet = fs.readFileSync(path.join(root, "assets/studio.css"), "utf8"), packageScript = fs.readFileSync(path.join(root, "scripts/package.ps1"), "utf8");
for (const token of ["-Recurse -File", "RelativePath", "DestinationDirectory"]) if (!packageScript.includes(token)) errors.push(`Theme package must retain nested portfolio assets: ${token}`);
for (const token of ["--paper: #ede6d8", "--ivory: #f7f1e7", "--stone: #cdbfa9", "--black: #12110f"]) if (!stylesheet.includes(token)) errors.push(`Warm palette token missing: ${token}`);
if (!/\.required-note\s*\{[\s\S]*?font-size:\s*14px\s*!important/.test(stylesheet)) errors.push("Required appointment guidance must remain at least 14px");
for (const legacy of ["#541d27", "#3c121a", "#d7b8b2", "--oxblood", "--wine", "--blush", "Price set in Shopify"]) { const sources = ["assets/studio.css", "config/settings_data.json", "config/settings_schema.json", ...previewFiles.map((file) => `preview/${file}`)]; if (sources.some((file) => fs.readFileSync(path.join(root, file), "utf8").includes(legacy))) errors.push(`Legacy palette or placeholder remains: ${legacy}`); }
const brandFiles = ["assets/studio.js", "config/settings_schema.json", ...fs.readdirSync(path.join(root, "sections")).filter((file) => file.endsWith(".liquid")).map((file) => `sections/${file}`), ...previewFiles.map((file) => `preview/${file}`)];
const exactWordmark = "<strong>BAMBÏ BEAUTY</strong><small>BOOKINGS</small>";
for (const file of brandFiles) { const source = fs.readFileSync(path.join(root, file), "utf8"); if (/Bambï Studio|<small>\s*STUDIO\s*<\/small>/i.test(source)) errors.push(`Retired Bambï Studio branding remains in ${file}`); for (const match of source.matchAll(/<a\s+class=["']wordmark["'][\s\S]*?<\/a>/gi)) if (!match[0].includes(exactWordmark)) errors.push(`Incorrect Bambï Beauty Bookings wordmark in ${file}`); }
const themeSettings = JSON.parse(fs.readFileSync(path.join(root, "config/settings_schema.json"), "utf8")); if (themeSettings[0]?.theme_name !== "Bambï Beauty Bookings") errors.push("Shopify theme name must be Bambï Beauty Bookings");
if (errors.length) { console.error(errors.join("\n")); process.exit(1); }
console.log(`Validated ${required.length} required theme files, seven merchant services, 18 portfolio assets, JSON schemas, booking properties and ${previewFiles.length} preview pages.`);
