import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(decodeURIComponent(new URL('..',import.meta.url).pathname).replace(/^\/(.:)/,'$1'));
const required=['layout/theme.liquid','templates/index.json','templates/collection.json','templates/product.json','templates/page.about.json','templates/page.preparation.json','templates/page.contact.json','templates/cart.json','sections/header.liquid','sections/footer.liquid','sections/hero-studio.liquid','sections/featured-services.liquid','sections/process.liquid','sections/main-booking-product.liquid','sections/main-collection.liquid','sections/main-rich-page.liquid','sections/main-contact.liquid','sections/main-cart.liquid','assets/studio.css','assets/studio.js','assets/studio-curly-install.jpg','config/settings_schema.json','config/settings_data.json','locales/en.default.json','scripts/build.mjs','vercel.json'];
let errors=[];for(const f of required)if(!fs.existsSync(path.join(root,f)))errors.push(`Missing ${f}`);
for(const dir of ['templates','config','locales','sections']){for(const f of fs.readdirSync(path.join(root,dir)).filter(x=>x.endsWith('.json'))){try{JSON.parse(fs.readFileSync(path.join(root,dir,f),'utf8'))}catch(e){errors.push(`Invalid JSON ${dir}/${f}: ${e.message}`)}}}
const product=fs.readFileSync(path.join(root,'sections/main-booking-product.liquid'),'utf8');for(const needle of ['properties[Appointment date]','properties[Appointment time preference]','properties[Preparation acknowledged]','content_for \'blocks\'','"type":"@app"'])if(!product.includes(needle))errors.push(`Booking section missing ${needle}`);
for(const file of fs.readdirSync(path.join(root,'preview')).filter(x=>x.endsWith('.html'))){const s=fs.readFileSync(path.join(root,'preview',file),'utf8');if(/https?:\/\/[^"']+\.(png|jpg|jpeg|webp)/i.test(s))errors.push(`External image URL in preview/${file}`)}
const hero=fs.readFileSync(path.join(root,'sections/hero-studio.liquid'),'utf8'),previewHome=fs.readFileSync(path.join(root,'preview/index.html'),'utf8'),script=fs.readFileSync(path.join(root,'assets/studio.js'),'utf8'),previewBundle=fs.readdirSync(path.join(root,'preview')).filter(x=>x.endsWith('.html')).map(x=>fs.readFileSync(path.join(root,'preview',x),'utf8')).join('\n');if(!hero.includes('studio-curly-install.jpg')||!previewHome.includes('studio-curly-install.jpg'))errors.push('Studio hero is not using the differentiated curly-install image');if(hero.includes('studio-hero.png')||previewHome.includes('studio-hero.png'))errors.push('Deprecated retail hero reference remains');for(const token of ['localStorage','bambiStudioAppointmentRequest','data-preview-cart','Clear request','Edit request'])if(!script.includes(token)&&!previewBundle.includes(token))errors.push(`Persisted request flow missing ${token}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log(`Validated ${required.length} required theme files, JSON schemas, booking properties and ${fs.readdirSync(path.join(root,'preview')).filter(x=>x.endsWith('.html')).length} preview pages.`);
